In [ ]:
from google.colab import files
import pandas as pd
import io
import numpy as np

In [ ]:
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['Hospital Emergency Room Data.csv']))
df.head()

Saving Hospital Emergency Room Data.csv to Hospital Emergency Room Data.csv

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,20-03-2024 08:47,H,Glasspool,M,69,White,NaN,False,10.0,39,False
1,316-34-3057,15-06-2024 11:29,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,True
2,897-46-3852,20-06-2024 09:13,P,Schubuser,F,56,African American,General Practice,True,9.0,55,True
3,358-31-9711,04-02-2024 22:34,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,True
4,289-26-0537,04-09-2024 17:48,Y,Gionettitti,Male,5,African American,Orthopedics,False,NaN,10,False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3816 entries, 2 to 9215
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient Id                  3816 non-null   object
 1   Patient Admission Date      3816 non-null   object
 2   Patient Gender              3816 non-null   object
 3   Patient Age                 3816 non-null   int64
 4   Patient Race                3816 non-null   object
 5   Department Referral         3816 non-null   object
 6   Patient Admission Flag      3816 non-null   object
 7   Patient Satisfaction Score  3816 non-null   int64
 8   Patient Waittime            3816 non-null   int64
 9   Patient Name                3816 non-null   object
dtypes: int64(3), object(7)
memory usage: 457.0+ KB

In [ ]:
df = df.drop(columns=["Patient Admission Flag.1"])
# one column is removed

In [ ]:
df["Patient Admission Flag"]=df["Patient Admission Flag"].replace({
    True:"Admitted",
    False:"Not Admitted"
})

In [ ]:
df.head()

,Patient Id,Patient Admission Date,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Name
2,897-46-3852,20-06-2024 09:13,Female,56,African American,General Practice,Admitted,9,55,P. Schubuser
3,358-31-9711,04-02-2024 22:34,Female,24,Native American/Alaska Native,General Practice,Admitted,8,31,U. Titcombe
4,289-26-0537,04-09-2024 17:48,Male,5,African American,Orthopedics,Not Admitted,0,10,Y. Gionettitti
10,497-14-6812,26-07-2024 01:45,Female,73,White,Gastroenterology,Admitted,0,34,Q. Churchard
11,393-38-9502,10-03-2024 22:02,Female,16,White,Orthopedics,Not Admitted,0,39,N. Corpes

In [ ]:
df["Patient Gender"]=df["Patient Gender"].replace({
      "M":"Male",
      "F":"Female"
    })

In [ ]:
df["Patient Name"] = df["Patient First Inital"] + ". " + df["Patient Last Name"]

In [ ]:
df = df.drop(columns="Patient First Inital")
df = df.drop(columns="Patient Last Name")

In [ ]:
df["Patient Satisfaction Score"] = df["Patient Satisfaction Score"].fillna(0).astype(int)

In [ ]:
df = df.dropna()
df = df.drop_duplicates()